version: '{build}'

skip_tags: true

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.3\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version

build_script:
  - mvn -B clean install

cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2 -> pom.xml

